# Generated by Django 4.0.4 on 2022-06-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemodel',
            old_name='author_id',
            new_name='author',
        ),
    ]
