# Generated by Django 4.0.4 on 2022-06-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_rename_author_id_articlemodel_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemodel',
            old_name='Aged',
            new_name='aged',
        ),
    ]
