# Generated by Django 4.0.4 on 2022-06-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_articlecomment_article_alter_userlike_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlelist',
            name='poster',
            field=models.FileField(default='Uploaded_Files/<django.db.models.fields.CharField>.jpg', upload_to='Uploaded_Files/'),
        ),
    ]
