# Generated by Django 4.0.4 on 2022-06-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlelist_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelist',
            name='poster',
            field=models.FileField(upload_to='Uploaded_Files/'),
        ),
    ]
