# Generated by Django 4.0.4 on 2022-06-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_rename_aged_articlemodel_aged'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='poster',
            field=models.CharField(default='', max_length=256),
        ),
    ]
