# Generated by Django 4.0.4 on 2022-06-03 12:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0005_tweetcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TweetComment',
            new_name='ArticleComment',
        ),
    ]
