# Generated by Django 4.0.4 on 2022-06-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_userlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='tweet',
            new_name='article',
        ),
    ]
