# Generated by Django 4.0.5 on 2022-06-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_articlerecomm'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlelist',
            name='aged',
            field=models.IntegerField(default=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlelist',
            name='aired_date',
            field=models.CharField(default='2020-07-22', max_length=256),
            preserve_default=False,
        ),
    ]
